services:
  - type: web
    name: notepad-app
    plan: free
    env: node
    region: singapore
    buildCommand: npm install && npm run migrate && npm run build
    startCommand: npm start
    envVars:
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
